/****************************************************************************
** Form interface generated from reading ui file 'FormConfig.ui'
**
** Created: mer. mai 4 22:17:02 2011
**
** WARNING! All changes made in this file will be lost!
****************************************************************************/

#ifndef FORMCONFIG_H
#define FORMCONFIG_H

#include <qvariant.h>
#include <qdialog.h>

class QVBoxLayout;
class QHBoxLayout;
class QGridLayout;
class QSpacerItem;
class QPushButton;
class QListBox;
class QListBoxItem;
class QWidgetStack;
class QWidget;
class QTextEdit;
class QLineEdit;
class QLabel;
class QFrame;
class QCheckBox;
class QComboBox;
class QSpinBox;
class QTabWidget;
class QButtonGroup;
class QRadioButton;
class QListView;
class QListViewItem;

class FormConfig : public QDialog
{
    Q_OBJECT

public:
    FormConfig( QWidget* parent = 0, const char* name = 0, bool modal = FALSE, WFlags fl = 0 );
    ~FormConfig();

    QPushButton* buttonHelp;
    QPushButton* buttonOk;
    QPushButton* buttonCancel;
    QListBox* listBox;
    QWidgetStack* m_WidgetStack;
    QWidget* Analyse;
    QTextEdit* msgConfig;
    QWidget* Repertoires;
    QLineEdit* repTmpGeneral;
    QPushButton* but_RepGlossaire;
    QLabel* lblRepGlossaire;
    QLabel* lblRepTmpGeneral;
    QPushButton* but_RepAide;
    QLabel* lblAide;
    QLineEdit* Aide;
    QPushButton* but_tmpRepTmp;
    QLineEdit* repGlossaire;
    QFrame* line_repAppli;
    QFrame* line_RepMask;
    QLabel* lblGestUser;
    QLineEdit* GestContact;
    QLineEdit* GestUser;
    QFrame* line_Contact;
    QLabel* textLabel2_3_2;
    QLabel* titreGestUser;
    QLabel* titreRep;
    QLabel* lblGestContact;
    QLabel* lblDefautVigie;
    QLineEdit* defautVigie;
    QPushButton* but_MasqueVigie;
    QPushButton* but_AppliUtilisateur;
    QPushButton* but_AppliContact;
    QWidget* General;
    QFrame* line_Themes;
    QLabel* textLabel3;
    QCheckBox* boxNouveauDossier;
    QFrame* line_Demarrage;
    QComboBox* m_Combo_Themes;
    QLabel* textLabel2;
    QCheckBox* boxConcurrent;
    QFrame* line_GestDoss;
    QLabel* textLabel1;
    QCheckBox* boxVerificationDossier;
    QLabel* textLabel7;
    QCheckBox* boxSplashScreen;
    QSpinBox* spinBox_menus_FontSize;
    QLabel* textLabel_DefMenuFontSize;
    QWidget* AccesRpide;
    QTabWidget* tabRapidAccess;
    QWidget* tab;
    QCheckBox* boxDockRapidAccess_Obs;
    QLabel* lblRepPDF_2;
    QCheckBox* boxDockRapidAccess_Terrain;
    QCheckBox* boxDockRapidAccess_Prescr;
    QFrame* line_MenAccRap;
    QLabel* textLabel_DockFntSize;
    QCheckBox* boxDockRapidAccess_Ident;
    QLabel* lblTitrePDF_1_2;
    QSpinBox* spinBoxDockRapidAccess_FontSize;
    QCheckBox* boxDockRapidAccess_OpenDoc;
    QLabel* lblRepPDF_2_3;
    QCheckBox* boxDockRapidAccess_OpenVars;
    QCheckBox* boxDockRapidAccess_OpenObs;
    QCheckBox* boxDockRapidAccess_OpenPrescr;
    QCheckBox* boxDockRapidAccess_OpenIntervenants;
    QCheckBox* boxDockRapidAccess_OpenIdent;
    QCheckBox* boxDockRapidAccess_OpenTerrain;
    QCheckBox* boxDockRapidAccess_OpenATCD;
    QCheckBox* boxDockRapidAccess_OpenVisuNote;
    QCheckBox* boxDockRapidAccess_Doc;
    QCheckBox* boxDockRapidAccessIntervenants;
    QWidget* tab_2;
    QLabel* lblRepPDF_2_3_2;
    QLabel* lblRepPDF_2_2;
    QLabel* textLabel2_2;
    QCheckBox* boxDockRapidAccess_Glossaire;
    QButtonGroup* buttonGroup1;
    QRadioButton* radioOpenCMDI;
    QRadioButton* radioOpenParent;
    QFrame* line_FoncGlo;
    QFrame* line_RubAct;
    QWidget* ListeMenus;
    QPushButton* but_MenuImages;
    QLabel* textLabel2_3;
    QLineEdit* menuImage;
    QFrame* line_DocList;
    QLabel* lblMenuImages;
    QPushButton* pushButtonAddRubrique;
    QListView* listViewRubParameters;
    QWidget* Docks;
    QCheckBox* boxDockRapidAccess;
    QFrame* line_MenuGlo;
    QFrame* line_MenuAccesRapide;
    QLabel* lblTitrePDF_1_2_3;
    QLabel* lblTitrePDF_1_2_2;
    QCheckBox* boxDockGlossaire;
    QLabel* lblTitrePDF_1_2_2_2;
    QFrame* line_MenuRub;
    QLabel* lblTitrePDF_1_2_2_2_2;
    QCheckBox* boxDockBarreOnglets;
    QCheckBox* boxDockRubriques;
    QFrame* line_MenuRub_Onglet;
    QWidget* CCAM;
    QPushButton* but_CCAMExe;
    QLabel* lblCCAMExe;
    QFrame* line_Exemple;
    QLabel* lblCCAMPrefixe_2;
    QLineEdit* CCAMExe;
    QLineEdit* CCAMCodePrefixe;
    QLineEdit* CCAMPrefixe;
    QLabel* lblCCAMPrefixe;
    QLabel* textLabel2_2_2_4;
    QLabel* lblCCAMPostfixe;
    QLineEdit* CCAMIni;
    QComboBox* CCAMPanneau;
    QLabel* lblCCAMIni;
    QPushButton* but_CCAMConfig;
    QLabel* lblCCAMPostfixe_2;
    QLabel* textLabel2_2_2_4_2;
    QFrame* line_PresCCAM;
    QLabel* lblCCAMPanneau;
    QLineEdit* CCAMPostfixe;
    QTextEdit* textCCAMView;
    QLineEdit* CCAMCodePostfixe;
    QWidget* PDF;
    QLineEdit* repDefautPDF;
    QPushButton* but_AppliPdftk;
    QPushButton* but_RepDesPDF;
    QLabel* lblRepPDFTmp;
    QLineEdit* appliPDF;
    QFrame* line_Appli;
    QPushButton* but_VisuPDF;
    QLabel* lblRepPdftk;
    QLabel* lblAppliPDF;
    QLineEdit* repPdftk;
    QPushButton* but_RepTmpPDF;
    QLabel* lblInfoPDF;
    QFrame* line_Info;
    QLabel* lblTitrePDF_2;
    QLabel* lblRepPDF;
    QLabel* lblTitrePDF_1;
    QLineEdit* repPDFTmp;

    QString m_DockMenu_OpenInterv;
    QString m_TabRubriques;
    QString m_DockMenu_OpenVisuNote;
    bool m_ParentInBold;
    QString m_Dock_Glossaire;
    QString m_MaxIamgeWidth;
    QString m_RepDocuments;
    QString m_Theme;
    QString m_erreur;
    bool m_erreurDrTuxIni;
    QString m_varErreurDrTuxIni;
    bool m_CheckErreur;
    QString m_CheckMsgErreur;
    QString m_SplashScreen;
    QString m_ZoomObs;
    QString m_ZoomPrescr;
    QString m_NouveauDossier;
    QString m_DossierConcurrent;
    QString m_CCAMLibPref;
    QString m_CCAMLibPostf;
    QString m_CCAMCodePref;
    QString m_CCAMCodePostf;
    QString m_CCAMPanneau;
    QString m_VerifDoss;
    QString m_IniParam;
    QString m_Dock_TabRubrique;
    QString m_DockMenu_OnScreen;
    QString m_DockMenu_ShowTerrain;
    QString m_DockMenu_ShowObs;
    QString m_DockMenu_ShowPrescr;
    QString m_DockMenu_ShowDoc;
    QString m_DockMenu_ShowIdent;
    QString m_DockMenu_Glossaire;
    QString m_DockMenu_DefaultFontSize;
    QString m_IniUser;
    QString m_PathAppli;
    QString m_DockMenu_OpenIdent;
    QString m_DockMenu_OpenATCD;
    QString m_DockMenu_OpenVars;
    QString m_DockMenu_OpenObs;
    QString m_DockMenu_OpenPrescr;
    QString m_DockMenu_OpenDoc;
    QString m_DockMenu_OpenTerrain;
    QString m_DockMenu_ClickBehavior;
    QString m_PopMenu_DefaultFontSize;

    void init();
    virtual bool checkError();
    virtual bool checkIni();
    virtual void specialBoxes();
    virtual void CCAMViewUpdate();
    virtual int checkFile( QString path, QLabel & lbl, int exe, bool w );
    virtual int checkDir( QString path, QLabel & lbl );
    virtual void checkParam();
    virtual bool getErreurIni();
    virtual QString getMsgErreurIni();
    virtual bool getErreurCheck();
    virtual QString getMsgErreurCheck();
    virtual void grabPDFIni( QString & pdfPath, QString & pdftkPath, QString & visualPDF, QString & tmpPath );
    virtual void getPrivateVariable();
    virtual void writeAllParams();
    virtual QString getDirectory( QString initialPath, const char * message );
    virtual QString getFile( QString initialPath, const char * message, bool typePath );

public slots:
    virtual void init_listViewRubParameters();
    virtual void listViewRubParameters_doubleClicked( QListViewItem * pQListViewItem, const QPoint &, int );
    virtual void AddNewRub();
    virtual void save_listViewRubParameters();
    virtual void setParams( const char * ParamsOfAppli, const char * ParamsOfUser, const char * PathOfAppli );
    virtual void getParams( QString & ParamsOfAppli, QString & ParamsOfUser );
    virtual void readVarString( QString def, QLabel & label, QLineEdit & lineedit );
    virtual void readVarString( QString & param, QString def, QLabel & label, QSpinBox * spinbox );
    virtual void readVarString( QString & param, QString def, QLabel & pW1, QLineEdit & pW2 );
    virtual void readVarString( QString & param, QString def, QLabel & pW1, QComboBox & pW2 );
    virtual void readVarString( QString & param, QString defaut, QCheckBox & pW1, const char * ValPourOui, const char * ValPourNon );
    virtual void buttonHelp_clicked();
    virtual void CCAMPrefixe_textChanged( const QString & );
    virtual void CCAMPostfixe_textChanged( const QString & );
    virtual void CCAMCodePrefixe_textChanged( const QString & );
    virtual void CCAMCodePostfixe_textChanged( const QString & );
    virtual void buttonOk_clicked();
    virtual void listBox_highlighted( int id );
    virtual void but_MenuImages_clicked();
    virtual void but_tmpRepTmp_clicked();
    virtual void but_RepGlossaire_clicked();
    virtual void but_RepAide_clicked();
    virtual void but_MasqueVigie_clicked();
    virtual void but_AppliContact_clicked();
    virtual void but_AppliUtilisateur_clicked();
    virtual void but_CCAMExe_clicked();
    virtual void but_CCAMConfig_clicked();
    virtual void but_RepDesPDF_clicked();
    virtual void but_RepTmpPDF_clicked();
    virtual void but_AppliPdftk_clicked();
    virtual void but_VisuPDF_clicked();
    virtual void pushButtonAddRubrique_clicked();

protected:
    QString m_DockMenu_ShowInterv;

    QGridLayout* FormConfigLayout;
    QHBoxLayout* Layout1;
    QSpacerItem* Horizontal_Spacing2;
    QGridLayout* AnalyseLayout;
    QGridLayout* RepertoiresLayout;
    QSpacerItem* spacer39_3_4;
    QSpacerItem* spacer39_8;
    QSpacerItem* spacer39_2_4;
    QSpacerItem* spacer39_10;
    QSpacerItem* spacer39_2_6;
    QSpacerItem* spacer39_2_5_3;
    QSpacerItem* spacer63;
    QGridLayout* GeneralLayout;
    QSpacerItem* spacer2_3_4;
    QSpacerItem* spacer2_2_2_2;
    QSpacerItem* spacer2_3;
    QSpacerItem* spacer2;
    QSpacerItem* spacer2_3_2;
    QSpacerItem* spacer2_2;
    QSpacerItem* spacer2_2_2_4;
    QSpacerItem* spacer2_3_3;
    QSpacerItem* spacer2_2_2;
    QSpacerItem* spacer2_2_2_3;
    QSpacerItem* spacer25_6_2;
    QSpacerItem* spacer12_2_2;
    QSpacerItem* spacer67;
    QGridLayout* AccesRpideLayout;
    QGridLayout* tabLayout;
    QSpacerItem* spacer12_2;
    QSpacerItem* spacer13;
    QSpacerItem* spacer13_2;
    QSpacerItem* spacer25_3;
    QSpacerItem* spacer25_4;
    QSpacerItem* spacer25_2;
    QSpacerItem* spacer12_3;
    QSpacerItem* spacer13_3;
    QSpacerItem* spacer13_4;
    QSpacerItem* spacer25_6;
    QSpacerItem* spacer25;
    QSpacerItem* spacer83;
    QSpacerItem* spacer13_5_2_2_2;
    QSpacerItem* spacer13_6;
    QSpacerItem* spacer25_8;
    QSpacerItem* spacer25_4_2;
    QSpacerItem* spacer25_5_2_2;
    QSpacerItem* spacer13_5_2;
    QSpacerItem* spacer13_2_2;
    QSpacerItem* spacer13_5_2_2;
    QSpacerItem* spacer13_5_2_2_2_2;
    QSpacerItem* spacer13_5_2_2_3;
    QSpacerItem* spacer12_3_2;
    QSpacerItem* spacer25_3_2;
    QSpacerItem* spacer13_4_2;
    QSpacerItem* spacer13_5_2_2_3_2;
    QSpacerItem* spacer13_2_2_2;
    QSpacerItem* spacer25_5_2;
    QSpacerItem* spacer25_2_2_2;
    QSpacerItem* spacer25_2_2;
    QSpacerItem* spacer13_3_2;
    QSpacerItem* spacer13_5;
    QSpacerItem* spacer25_5;
    QSpacerItem* spacer25_5_3;
    QSpacerItem* spacer13_5_3;
    QGridLayout* tabLayout_2;
    QSpacerItem* spacer12_4_2;
    QSpacerItem* spacer84;
    QSpacerItem* spacer12_4;
    QSpacerItem* spacer12_3_2_2;
    QGridLayout* buttonGroup1Layout;
    QGridLayout* ListeMenusLayout;
    QSpacerItem* spacer34_4_2;
    QGridLayout* layout2;
    QSpacerItem* spacer34_4;
    QGridLayout* DocksLayout;
    QSpacerItem* spacer25_7;
    QSpacerItem* spacer12;
    QSpacerItem* spacer25_7_2;
    QSpacerItem* spacer12_4_3;
    QSpacerItem* spacer62;
    QSpacerItem* spacer12_4_4;
    QSpacerItem* spacer25_7_3;
    QSpacerItem* spacer12_4_4_2;
    QSpacerItem* spacer25_7_3_2;
    QGridLayout* CCAMLayout;
    QSpacerItem* spacer39_3_2;
    QSpacerItem* spacer39_6;
    QSpacerItem* spacer64;
    QSpacerItem* spacer39_7;
    QSpacerItem* spacer39_2_3;
    QSpacerItem* spacer39_3_3;
    QSpacerItem* spacer39_2_2;
    QSpacerItem* spacer39_4_2;
    QSpacerItem* spacer39_4_3;
    QGridLayout* PDFLayout;
    QSpacerItem* spacer65;
    QSpacerItem* spacer39_3;
    QSpacerItem* spacer39_2;
    QSpacerItem* spacer39;
    QSpacerItem* spacer39_4;
    QSpacerItem* spacer39_5;

protected slots:
    virtual void languageChange();

};

#endif // FORMCONFIG_H
