#!/bin/bash



echo '========== Installation de QLightPad en cours ================'
cd qlightpad/src
qmake src.pro
make
make clean
rm Makefile
cd ../bin
strip -s QLightPad
./QLightPad QLightPadSys/Welcome.html



